services:
  - type: web
    name: flux-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: HF_API_KEY
        sync: false  # You will set this securely in the Render dashboard
